feat:TransactionHistory.js UI 작업
bunderLikeLion/sellon_frontend pull request #76
Opened 2022-08-07 18:37 UTC by yoojinyang0303

## 작업 내용
- TransactionHistory.js UI 작업

## 참고 자료
- 

## 기타 사항
- 

## 희망 완료일
-

2022-08-07 19:05 UTC, sh981013s requested changes
리뷰 확인해주세요~

2022-08-08 13:37 UTC, yoojinyang0303 commented
피드백 반영하여 수정했습니다. 리뷰 부탁드려요!!

2022-08-08 17:23 UTC, sh981013s requested changes
아코디언 1개만 남겨주세요~

2022-08-08 17:33 UTC, sh981013s requested changes
border-radius rem 으로 단위 변경 부탁드려요~

2022-08-08 17:42 UTC, sh981013s approved these changes
굳굳 merge 진행해주세요~

2022-08-08 17:47 UTC, merged